language: python
python:
  - "3.6"

# easiest way of getting rtree
before_install:
  - sudo apt update
  - sudo apt install libspatialindex-dev

# command to install dependencies
install:
  - pip install wheel
  - pip install Rtree
  - pip install -r requirements.txt

# command to run tests
script:
  - make test
